/// Serialises an `MlirModule` to a `.mlir` text file.

use std::io::Write;
use std::path::Path;

use super::context::MlirModule;

pub fn emit(module: &MlirModule, output: &Path) {
    let mut file = std::fs::File::create(output)
        .unwrap_or_else(|e| panic!("cannot create {}: {e}", output.display()));

    writeln!(file, "// Generated by aether-tensor-lang").unwrap();
    writeln!(file, "module {{").unwrap();
    for op in module.ops() {
        writeln!(file, "  {op}").unwrap();
    }
    writeln!(file, "}}").unwrap();
}
